name: Revert
on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@main
      with:
        submodules: 'false'
        
    - name: Revert
      run: |
        chmod 777 ./stuck.diff
        git apply ./stuck.diff
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Revert"
        git push
